### ISSUE TITLE
Qstn re gt homography H12p

### ISSUE THREAD

**Issue by nudro** [kornia/kornia-examples#20]
I'm following: https://kornia-tutorials.readthedocs.io/en/latest/homography.html and https://github.com/kornia/kornia/blob/master/examples/homography_regression/homography.ipynb. 

Specifically in: 

```
dst_homo_src_gt = np.loadtxt('H1to2p')
dst_homo_src_gt = torch.from_numpy(dst_homo_src_gt)[None].float().to(device)
print(dst_homo_src_gt.shape)
print(dst_homo_src_gt)

```

How did you compute / where did you get the `H1to2p`.txt file?

**Comment by edgarriba** [comment]
is part of this dataset: https://www.robots.ox.ac.uk/~vgg/data/affine/

**Comment by edgarriba** [comment]
Besides, I suggest to check this updated version: https://kornia-tutorials.readthedocs.io/en/latest/homography.html

**Comment by nudro** [comment]
Thanks
